version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=user                      # user
      - POSTGRES_PASSWORD=password              # password
      - POSTGRES_DB=match-betting-database      # database name
    volumes:
      - postgres-data:/var/lib/postgresql/data  # database storage
    networks:
      - app-network
    ports:
      - "5432:5432"                             # port for communication

networks:
  app-network:
    driver: bridge                              # connecting containers in the same network

volumes:
  postgres-data:
