version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=user                      # użytkownik
      - POSTGRES_PASSWORD=password              # hasło
      - POSTGRES_DB=match-betting-database      # nazwa bazy danych
    volumes:
      - postgres-data:/var/lib/postgresql/data  # przechowywanie danych bazy
    networks:
      - app-network
    ports:
      - "5432:5432"                             # port do komunikacji z bazą

networks:
  app-network:
    driver: bridge                              # połączenie kontenerów w tej samej sieci

volumes:
  postgres-data:
